backend/models/Komunitas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "komunitas".
 *
 * @property int $id
 * @property string $nama
 * @property string $deskripsi
 * @property string $foto
 * @property string $contact
 * @property string $address
 * @property int $id_admin_komunitas
 * @property string $created
 *
 * @property User $adminKomunitas
 * @property Komunitasmember[] $komunitasmembers
 * @property Project[] $projects
 */
class Komunitas extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'komunitas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'deskripsi', 'contact', 'address', 'id_admin_komunitas'], 'required'],
            [['nama', 'deskripsi', 'contact', 'address'], 'string'],
            [['id_admin_komunitas'], 'integer'],
            [['created'], 'safe'],
            [['foto'], 'string', 'max' => 200],
            [['id_admin_komunitas'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_admin_komunitas' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'deskripsi' => 'Deskripsi',
            'foto' => 'Foto',
            'contact' => 'Contact',
            'address' => 'Address',
            'id_admin_komunitas' => 'Id Admin Komunitas',
            'created' => 'Created',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdminKomunitas()
    {
        return $this->hasOne(User::className(), ['id' => 'id_admin_komunitas']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKomunitasmembers()
    {
        return $this->hasMany(Komunitasmember::className(), ['id_komunitas' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(Project::className(), ['id_komunitas' => 'id']);
    }
}

frontend/models/Komunitas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "komunitas".
 *
 * @property int $id
 * @property string $nama
 * @property string $deskripsi
 * @property resource $foto
 * @property string $contact
 * @property string $address
 * @property int $id_admin_komunitas
 * @property string $created
 *
 * @property User $adminKomunitas
 */
class Komunitas extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'komunitas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'deskripsi', 'contact', 'address', 'id_admin_komunitas'], 'required'],
            [['nama', 'deskripsi', 'contact', 'address'], 'string'],
            [['contact'],'string','max'=>'12','min'=>'6'],
            [['foto'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg,jpeg'],
            [['id_admin_komunitas'], 'integer'],
            [['created'], 'safe'],
            [['id_admin_komunitas'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_admin_komunitas' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'deskripsi' => 'Deskripsi',
            'foto' => 'Logo Komunitas',
            'contact' => 'Contact',
            'address' => 'Address',
            'id_admin_komunitas' => 'Id Admin Komunitas',
            'created' => 'Created',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdmin() {
        return $this->hasOne(User::className(), ['id' => 'id_admin_komunitas']);
    }
}

backend/controllers/KomunitasController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Komunitas;
use app\models\KomunitasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * KomunitasController implements the CRUD actions for Komunitas model.
 */
class KomunitasController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Komunitas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KomunitasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Komunitas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Komunitas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Komunitas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Komunitas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Komunitas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Komunitas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Komunitas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Komunitas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/KomunitasController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Komunitas;
use app\models\Komunitasmember;
use app\models\KomunitasSearch;
use app\models\KomunitasmemberSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * KomunitasController implements the CRUD actions for Komunitas model.
 */
class KomunitasController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Komunitas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = Komunitas::find()->all();

        return $this->render('index', [
            'model'=>$model,
        ]);
    }

    /**
     * Displays a single Komunitas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Komunitas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Komunitas();
        $komunitasmember = new Komunitasmember();
        $foto = UploadedFile::getInstance($model, 'foto');

        if ($model->load(Yii::$app->request->post())) {
            if(!empty($foto)){
              $foto->saveAs(Yii::getAlias('@frontend/web/uploads/').'komunitas'.$model->nama.'.'. $foto->extension);
              $model->foto = 'komunitas'.$model->nama.'.'.$foto->extension;
              $model->save(FALSE);
            }
            $komunitasmember->id_komunitas = $model->id;
            $komunitasmember->id_user = $model->id_admin_komunitas;
            $komunitasmember->status = 1;
            $komunitasmember->role = 1;
            $komunitasmember->save();
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionListmanagekomunitas($id)
    {
      $joinedcommunity = Yii::$app->db->createCommand('SELECT k.id, k.nama FROM komunitasmember km, komunitas k WHERE km.id_komunitas=k.id AND id_user=:id AND role=2')
           ->bindValue(':id', $id)
           ->queryAll();
      return $this->render('listmanagekomunitas',[
        'model'=>$joinedcommunity,
      ]);
    }

    public function actionManagekomunitas($id_komunitas,$id_user)
    {
      $searchModel = new KomunitasmemberSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
      $dataProvider->query->andWhere('komunitasmember.id_komunitas = '.$id_komunitas);
      $model = $this->findModel($id_komunitas);
      return $this->render('managekomunitas', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
          'model'=>$model,
          'id_komunitas'=>$id_komunitas,
      ]);
    }
    public function actionBroadcast($id_komunitas)
    {
      $model=new Komunitas();
      return $this->render('broadcast',[
        'model'=>$model,
        'id_komunitas'=>$id_komunitas,
      ]);
    }
    public function actionSendbroadcast($id_komunitas)
    {
      $data=Yii::$app->request->get();
      $model = Yii::$app->db->createCommand('SELECT k.id, km.id_user, u.contact FROM komunitasmember km, komunitas k,user u WHERE km.id_komunitas=k.id AND id_komunitas=:id_komunitas AND km.status=1 AND km.id_user = u.id')
           ->bindValue(':id_komunitas', $id_komunitas)
           ->queryAll();
      foreach($model as $models)
      {
        $nohp=$models['contact'];
        $messages=$data['Komunitas']['deskripsi'];
        $curl = curl_init();

        curl_setopt_array($curl, array(
          CURLOPT_URL => "http://api.mainapi.net/smsnotification/1.0.0/messages",
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => "",
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 30,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => "POST",
          CURLOPT_POSTFIELDS => "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"msisdn\"\r\n\r\n".$nohp."\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"content\"\r\n\r\n".$messages."\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--",
          CURLOPT_HTTPHEADER => array(
            "Authorization: Bearer 66fa2015aeca846426549e3baaa6a5f7",
            "Cache-Control: no-cache",
            "Postman-Token: bb826273-2664-bfd3-d3a2-673f55e071d5",
            "content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW"
          ),
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);
        $mes='';
        if ($err) {
          echo "cURL Error #:" . $err;
        } else {
          echo $response;
        }
      }
      return $this->redirect('index');
      /*
      */
    }

    public function actionKonfirmasi($id,$status,$id_komunitas,$id_user)
    {
      $model = new Komunitasmember();
      $model=$model->findOne($id);
      $model->status=$status;
      //role 0=non member,1=member,2=admin
      if($status==1)
      {
        $model->role=1;
      }else if($status==2){
        $model->role=0;
      }
      $model->save();
      return $this->redirect(['managekomunitas','id_komunitas'=>$id_komunitas,'id_user'=>$id_user]);
    }

    public function actionSetadmin($id,$status,$id_komunitas,$id_user)
    {
        $model = new Komunitasmember();
        $model = $model->findOne($id);
        $model->role=2;
        $model->save();
        return $this->redirect(['managekomunitas','id_komunitas'=>$id_komunitas,'id_user'=>$id_user]);
    }

    /**
     * Updates an existing Komunitas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $foto = UploadedFile::getInstance($model, 'foto');

        if ($model->load(Yii::$app->request->post())) {
            if (!empty($foto)) {
                  $foto->saveAs(Yii::getAlias('@frontend/web/uploads/') . 'komunitas'.$id.'.' . $foto->extension);
                  $model->foto = 'komunitas'.$model->id.'.' . $foto->extension;
                  $model->save(FALSE);
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Komunitas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Komunitas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Komunitas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Komunitas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/komunitas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Komunitas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="komunitas-form">
    <div class="row">
      <div class="col-lg-8 boxform">
        <h1><p class="text-center">Form Register Komunitas</p></h1>
        <?php $form = ActiveForm::begin(
          ['options' => ['enctype' => 'multipart/form-data']]) ?>

        <?= $form->field($model, 'nama')->textInput(['placeholder'=>'Input Nama Komunitas'])->label(false) ?>

        <?= $form->field($model, 'deskripsi')->textarea(['rows' => 6,'placeholder'=>'Deskripsi Komunitas'])->label(false) ?>

        <?= $form->field($model, 'foto')->fileInput(['class'=>'form form-inline']) ?>

        <?= $form->field($model, 'contact')->textInput(['placeholder'=>'Nomor Telp/Hp'])->label(false) ?>

        <?= $form->field($model, 'address')->textarea(['rows' => 3,'placeholder'=>'Alamat'])->label(false) ?>

        <?php echo $form->field($model, 'id_admin_komunitas')
          ->hiddenInput(['value' => Yii::$app->user->identity->id])
          ->label(false);
          ?>

        <div class="form-group">
            <?= Html::submitButton('Register', ['class' => 'btn btn-success buttonfull']) ?>
            <p class="text-center"><small>Dengan melakukan register berarti anda menyetujui<br>terms and condition carelaig</small></p>
        </div>

        <?php ActiveForm::end(); ?>
      </div>

    </div>


</div>

frontend/views/komunitas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\KomunitasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="komunitas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'deskripsi') ?>

    <?= $form->field($model, 'foto') ?>

    <?= $form->field($model, 'contact') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'id_admin_komunitas') ?>

    <?php // echo $form->field($model, 'created') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/komunitas/broadcast.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $searchModel app\models\KomunitasmemberSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Broadcast Message ';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="komunitasmember-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
      <div class="col-lg-8 boxform">
        <?php $form = ActiveForm::begin(
          ['options' => ['enctype' => 'multipart/form-data'],
              'method' => 'get',
              'action' => ['sendbroadcast', 'id_komunitas' => $id_komunitas]
          ]) ?>
        <?= $form->field($model, 'deskripsi')->textarea(['rows' => 6,'placeholder'=>'Broadcast'])->label(false) ?>
        <div class="form-group">
            <?= Html::submitButton('Broadcast', ['class' => 'btn btn-success buttonfull']) ?>
        </div>
        <?php ActiveForm::end(); ?>
      </div>
    </div>
</div>

frontend/views/komunitas/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Komunitas */

$this->title = 'Daftar Komunitas';
$this->params['breadcrumbs'][] = ['label' => 'Komunitas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="komunitas-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
<?php
$this->registerCssFile("@web/css/carelaig.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
], 'css-print-theme');
?>

frontend/views/komunitas/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\KomunitasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Komunitas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="komunitas-index">

    <div class="row">
    <?php

      foreach($model as $models)
      {
        $link = Html::a(
          $models->nama,
          Url::to(['/komunitas/view','id'=>$models->id]),
          ['class'=>'tulisannamakomunitas']
        );
        $max_length = 200;
        $s=$models->deskripsi;
        if (strlen($s) > $max_length)
        {
            $offset = ($max_length - 3) - strlen($s);
            $s = substr($s, 0, strrpos($s, ' ', $offset)) . '...';
        }
        $buttondaftar =  Html::a(
                          'Daftar Member',
                          Url::to(['/komunitasmember/create', 'id_komunitas' => $models->id]),
                          [
                              'class'=>'btn btn-primary',
                          ]
                        );
        $buttonreadmore = Html::a(
                              'Read More',
                              Url::to(['/komunitas/view', 'id' => $models->id]),
                              [
                                  'class'=>'btn btn-success',
                              ]
                          );
        echo '<div class="col-lg-4">';
        echo '<div class="box">';
        echo Html::img('@web/uploads/'.$models->foto, ['alt'=>'some', 'class'=>'imageprofilkomunitas']);
        echo '<div style="font-size:30px;"><p class="text-center">'.$link.'</p></div>';
        echo '<div class="paragraf">'.$s.'</div>';
        echo '<div class="paragraf">'.$buttonreadmore.' '.$buttondaftar.'</div>';
        echo '</div>';
        echo '</div>';
      }

    ?>


</div>
<?php
$this->registerCssFile("@web/css/carelaig.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
], 'css-print-theme');
?>

frontend/views/komunitas/listmanagekomunitas.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\KomunitasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Komunitas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="komunitas-index">
  <h4>List Komunitas</h4>
  <table class="table table-bordered">
    <tr>
      <th>No</th>
      <th>Nama Komunitas</th>
      <th>Action</th>
    </tr>
    <?php
      $no=1;
      foreach($model as $models)
      {
        echo '<tr>';
        echo '<td>'.$no.'</td>';
        echo '<td>'.$models['nama'].'</td>';
        echo '<td>'.Html::a('Manage', ['managekomunitas', 'id_komunitas' => $models['id'],'id_user'=>Yii::$app->user->identity->id], ['class' => 'btn btn-primary']).'</td>';
        echo '</tr>';
        $no++;
      }
    ?>
</table>

</div>
<?php
$this->registerCssFile("@web/css/carelaig.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
], 'css-print-theme');
?>

frontend/views/komunitas/managekomunitas.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\KomunitasmemberSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Komunitas '.$model->nama;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="komunitasmember-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= Html::a('Broadcast Message',
      Url::to(['broadcast','id_komunitas'=>$id_komunitas])
    , ['title' => 'broadcast','class'=>'btn btn-success']); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
              'attribute'=>'namaUser',
              'label'=>'Nama Member',
            ],
            [
              'attribute'=>'timestamp',
              'label'=>'Request Join Date',
              'value'=>function ($model, $index)
                      {
                        return date('Y-m-d',strtotime($model->timestamp));
                      }
            ],
            [
              'attribute'=>'status',
              'label'=>'Status',
              'value'=>function ($model, $index)
                      {
                        $label='Request Join';
                        if($model->status==1)
                        {
                          $label='Joined';
                        }
                        else if($model->status==2)
                        {
                          $label='Rejected';
                        }
                        return $label;
                      }
            ],
            [
              'attribute'=>'role',
              'label'=>'Role',
              'value'=>function ($model, $index)
                      {
                        $label='Non Member';
                        if($model->role==1)
                        {
                          $label='Member';
                        }
                        else if($model->role==2)
                        {
                          $label='Admin';
                        }
                        return $label;
                      }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{approve} {reject} {setadmin}',
                'header'=>'Action',
                'buttons' => [
                   'approve' => function ($url, $model) {
                      $url = Url::to(['konfirmasi', 'id' => $model->id,'status'=>1, 'id_komunitas'=>$model->id_komunitas,'id_user'=>Yii::$app->user->identity->id]);
                      $class='';
                      if($model->status==1)
                      {
                        $class='btn btn-success disabled';
                      }else{
                        $class='btn btn-success';
                      }
                      return Html::a('<span class="fa fa-check"></span>', $url, ['title' => 'approve','class'=>$class]);
                   },
                   'reject' => function ($url, $model) {
                       $url = Url::to(['konfirmasi', 'id' => $model->id,'status'=>2, 'id_komunitas'=>$model->id_komunitas,'id_user'=>Yii::$app->user->identity->id]);
                       $class='';
                       if($model->status==2)
                       {
                         $class='btn btn-danger disabled';
                       }else{
                         $class='btn btn-danger';
                       }
                       return Html::a('<span class="fa fa-times"></span>', $url, ['title' => 'reject','class'=>$class]);
                   },
                   'setadmin' => function ($url, $model) {
                        $class='btn btn-primary';
                        if($model->status==2)
                        {
                          $class='btn btn-primary disabled';
                        }
                       $url = Url::to(['setadmin', 'id' => $model->id,'status'=>1, 'id_komunitas'=>$model->id_komunitas,'id_user'=>Yii::$app->user->identity->id]);
                       return Html::a('Set Admin', $url, ['title' => 'setadmin','class'=>$class]);
                   },
                ]
            ]

          ,
        ],
    ]); ?>
</div>

frontend/views/komunitas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Komunitas */

$this->title = 'Update Komunitas: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Komunitas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="komunitas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/komunitas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Komunitas */

$this->title = $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Komunitas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="komunitas-view">
<h4><?= $model->nama ?></h4>
<div class="row">
  <div class="col-lg-3">
    <div class="box">
      <p class="text-center"><?= Html::img('@web/uploads/'.$model->foto, ['alt'=>'some', 'class'=>'imageprofilkomunitas']);?></p>
      <div class="paragraf">
        <table class="table table-striped">
          <tr>
            <td>admin komunitas : <?= $model->admin->name ?></td>
          </tr>
          <tr>
            <td>kontak : <?= $model->contact ?></td>
          </tr>
          <tr>
            <td>alamat : <?= $model->address ?></td>
          </tr>
          <tr>
            <td>jumlah member : <?= $model->address ?></td>
          </tr>
        </table>
        <p class="text-center"><?= Html::a('Daftar Member', ['/komunitasmember/create', 'id_komunitas' => $model->id], ['class'=>'btn btn-primary']) ?></p>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="box">
      <p class="paragraf"><?= $model->deskripsi ?></p>
    </div>
  </div>
</div>

</div>
<?php
$this->registerCssFile("@web/css/carelaig.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
], 'css-print-theme');
?>